AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EnvVarTest:
    Type: "AWS::Lambda::Function"
    Properties:
    Code:
      S3Bucket: dataflow-bucker
      S3Key: EnvVarTest.zip
    Runtime: python2.7
    Environment:
      Variables:
        TEST_ENV: it should work