AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Receives SNS message and publishes to SQS
Resources:
  SqsProducer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: SqsProducer.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Receives SNS message and publishes to SQS
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::869422924821:role/DataflowRole'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          TEST_ENV: this should work
  SNSTopic1:
    Type: 'AWS::SNS::Topic'